stages:
    - build

#    - preparation
#    - pre-build-tests
#    - post-build-tests
#    - package
#    - deploy
#    - cleanup

default:
    image: debian

install_packages:
    stage: preparation
    script:
        - apt-get update
        - apt-get -y install cmake make

linter:
    stage: pre-build-tests
    script:
        - echo

build:
    stage: build
    script:
        - apt-get update
        - apt-get -qq -y install cmake make gcc libsqlite3-dev
        - mkdir build
        - cd build
        - cmake ..
        - make all

unit_test:
    stage: pre-build-tests
    script:
        - echo

unit_test_multiple_times:
    stage: pre-build-tests
    script:
        - echo

coverage:
    stage: pre-build-tests
    script:
        - echo

regression_test:
    stage: post-build-tests
    script:
        - echo

upload_to_software_repository:
    stage: deploy
    script:
        - echo
    only:
        - tags

cleanup:
    stage: cleanup
    script:
        - echo
    when: always
